version: '3.8'

services:
  app:
    build:
      context: ../   # Đường dẫn tới thư mục gốc của dự án
      dockerfile: Dockerfile  # Đường dẫn tới Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
