version: '3.8'

services:
  app:
    build:
      context: ../   # Đường dẫn tới thư mục gốc của dự án
      dockerfile: Dockerfile  # Đường dẫn tới Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home

  registry:
    image: registry:2   # Sử dụng Docker Registry phiên bản 2
    ports:
      - "5000:5000"     # Port mặc định của Docker Registry
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - "8081:80"     # Port cho giao diện người dùng của Docker Registry
    environment:
      - REGISTRY_TITLE=Docker Registry UI
      - REGISTRY_URL=http://registry:5000   # URL của Docker Registry
    depends_on:
      - registry

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8929:8929"
      - "2224:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./certs:/etc/gitlab/ssl  # Đường dẫn tới thư mục chứa chứng chỉ SSL

volumes:
  mongo-data:
  jenkins-data:
  registry-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
